management:
  endpoints:
    web:
      exposure:
        include: "*"
    base-path: /actuator

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:9090

info:
  app:
    name: actuator-learn
    description: actuator-learn
    version: 1.0
    java.version: 1.8